### ISSUE TITLE
Cannot send message from the application

### ISSUE THREAD

**Issue by tusharthorat** [KanybekMomukeyev/FacebookChat#3]
I am trying to send message to facebook friend but the messages are not sent.
I am able to receive messages but cannot send messages.

**Comment by javalnanda** [comment]
I am also facing the same issue. Getting following error :
<message xmlns="jabber:client" type="error"><error code="501" type="modify"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></message>

**Comment by KanybekMomukeyev** [comment]
OK, i should move all included Libraries to Cocoapods,  then will Update all Libraries. 
Maybe  library XMPPFramework is outdated.

**Comment by javalnanda** [comment]
Solved the issue by replacing [message addAttributeWithName:@"xmlns" stringValue:@"http://www.facebook.com/xmpp/messages"];

with
[message addAttributeWithName:@"type" stringValue:@"chat"];

**Comment by KanybekMomukeyev** [comment]
Thanks javalnanda, closing this issue!
